usuario_invalido: 'EsseIdNaoExiste'
usuario_valido: '0uxuPY0cbmQhpEz1' #cuidar para nao deletar um id valido

usuario_admin:
  email: admin@email.com.br
  password: admin

usuario_nao_admin:
  email: naoadm@qa.com.br
  password: teste
